### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by ghost** [ethgent2391/iniGEN#4]
- [x] Create a GoogleDoc for the presentation
- [ ] Ethan uploads speaking content
- [ ] Yanni uploads speaking content
- [ ] Shawn uploads speaking content
- [x] George uploads speaking content

**Comment by ghost** [comment]
https://docs.google.com/presentation/d/1JJq7ngYTu8rGqoCuPU_OS3dmqrWoOivM5C0xUOGYq3o/edit?usp=sharing

**Comment by ethgent2391** [comment]
added speaker notes with global gaming stats to description slide. also added slide for example of .Ini file.
