### ISSUE TITLE
MySQL Database

### ISSUE THREAD

**Issue by ghost** [ethgent2391/iniGEN#5]
Project Requirement 2a
- [x] Create MySQL Database
- [x] Ensure group has access to the Database
- [x] Login info is stored in a .env file to ensure security
- [x] Create appropriate tables
- [x] Run tests to confirm app is able to run schema & seed files 
PLEASE ADD COMMENTS TO THIS ISSUE WHEN YOU CONFIRM SOMETHING IS WORKING
Don't just delete the issue.

**Comment by ethgent2391** [comment]
Created "Tables.sql" schema. this Drops ini database, creates a new one, then creates two tables: one for setting name, and the other for setting value. to be joined via ID.
